### PR TITLE
dev: Simplify quazip dependency code

### PR DESCRIPTION
**Pull request by JBBgameich**

### CODE REVIEW

**Comment by JBBgameich** [comment]
Just checked, this still breaks my setup but is simpler than the former solution at least.

**Comment by kaamui** [comment]
Hello,

I actually reverted the two commits you found on the dev branch regarding quazip. They indeed were not correct at all. I can't figure out why, but I still have, on a fresh install of Ubuntu 18.04, linking errors with quazip (undefined references to Qt5Core functions), using my own config, or yours (with the rewrite libs.pri commit you wrote on your own repo). I'll probably restart on this next month, starting with the work you and @sunweaver did.

Did you succed on building openboard on Ubuntu 18 with the native quazip5-dev package ?

**Comment by JBBgameich** [comment]
The linking bug is likely related to the co-existence of the quazip and quazip5 package. Only the quazip5 build has support for Qt5, so you need to link against quazip5.

**Comment by JBBgameich** [comment]
You can maybe reuse my code used for the debian package and flatpak, which succeeds finding quazip on ubuntu xenial and newer up to the current debian sid at least.
https://gitlab.com/JBBgameich/OpenBoard/commit/041f1bd5448fa6d443ef7768fa5d5147c2140aa8#085c0cc5fd94a1823c3dd645988e7df76535d7fe_0_3

**Comment by kaamui** [comment]
> You can maybe reuse my code used for the debian package and flatpak, which succeeds finding quazip on ubuntu xenial and newer up to the current debian sid at least.
> https://gitlab.com/JBBgameich/OpenBoard/commit/041f1bd5448fa6d443ef7768fa5d5147c2140aa8#085c0cc5fd94a1823c3dd645988e7df76535d7fe_0_3

I did, this morning, but I still have this linking error on quazip not finding qt5Core functions (with no pkgconfig support => 0.7.3-5ubuntu1). I do it on a fresh install, with nothing more than qtchooser, Qt5.5.1 installed, libquazip5-dev (and the libQt5Core.so.5.9 it installs with) and the others needed (for OpenGL, ffmpeg, gstreamer etc.)

Linking errors are generally quite simple to solve, but this one seems tricky ^^. For the co-existence with another quazip lib, I don't think there is any other quazip lib installed (quazip "Third Party" no more used, locate quazip only refers to quazip5 data). It may be a co-existence issue, between two Qt5Core (5.5 vs 5.9), but I didn't find anything on this... 

150 unresolved calls like this one ...
`/usr/lib/x86_64-linux-gnu/libquazip5.so:-1: erreur : undefined reference to QString::localeAwareCompare(QString const&) const@Qt_5`

Did you encounter it ? Did you try on Ubuntu 18.04 ?

Thank you for your help.

**Comment by JBBgameich** [comment]
I usually test on debian testing. I also built it successfully on KDE Neon 18.04, but they probably have their own quazip build. Maybe the problem is actually in the quazip package (just a guess)?

I'll quickly test the current dev branch on my GitLab CI setup and report back.

**Comment by kaamui** [comment]
Ok, thanks a lot. 

I hope the issue is on my side ^^, 'cause it could be a reason to maintain more longer than wanted the third-party build..

**Comment by JBBgameich** [comment]
My view might be a little biased, but wouldn't it make more sense for you as the project maintainer to provide e.g flatpak builds and let the distribution maintainers do the distro specific packaging? For example in a flatpak you could control the quazip build yourself without using prebuilts.

**Comment by JBBgameich** [comment]
The CI is git a Qt 5.12 bug, I put a workaround in place.
https://gitlab.com/JBBgameich/OpenBoard/pipelines/52965097

**Comment by kaamui** [comment]
> My view might be a little biased, but wouldn't it make more sense for you as the project maintainer to provide e.g flatpak builds and let the distribution maintainers do the distro specific packaging? For example in a flatpak you could control the quazip build yourself without using prebuilts.

It is in fact more complicated. Internally, the Openboard build I release on Github is embed in a whole delivery process and infrastructure configuration for Geneva schools. So there is a lot of things to consider, and time is not with me^^. So it is hard for me to evaluate what is the efficiency of the "package once/distribute everywhere" promise theses solutions make. But it could, one day, become something we introduce. This is why your work is pinned actually, to get more feedbacks ;)

**Comment by JBBgameich** [comment]
I see. If I can help with anything, let me know.

**Comment by JBBgameich** [comment]
Sorry for using this pull request as a chat, but do you think it would be possible to get the xpdf to poppler patch accepted? https://gitlab.com/JBBgameich/OpenBoard/commit/7179a33c0cbb6fe205d57ad854ddc5be4990e509
(I just want to check whether preparing another pr makes sense)

This change should remove the need for the xpdf source code dump in the ThirdParty repository by using the proper library.

**Comment by JBBgameich** [comment]
Btw, the dev branch builds correctly on KDE Neon 18.04 (based on Ubuntu 18.04). I only tested it with my patches though.
I'm still waiting for the ubuntu-bionic build (without KDE Neon additions) to finish.

**Comment by sunweaver** [comment]
Hi folks,

On  Do 21 Mär 2019 15:52:26 CET, JBB wrote:

> Sorry for using this pull request as a chat, but do you think it  
> would be possible to get the xpdf to poppler patch accepted?  
> https://gitlab.com/JBBgameich/OpenBoard/commit/7179a33c0cbb6fe205d57ad854ddc5be4990e509
> (I just want to check whether preparing another pr makes sense)
>
> This change should remove the need for the xpdf source code dump in  
> the ThirdParty repository by using the proper library.

I also apologize for abusing the issue tracker for chatting. Good to  
see that things are making progress here. After the Debian buster  
release, I will get back to pushing OpenBoard towards Debian once  
more. (Until the release of Debian 10, I am 100% busy with fixing bugs  
on my already maintained packages).

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by kaamui** [comment]
> Sorry for using this pull request as a chat, but do you think it would be possible to get the xpdf to poppler patch accepted? https://gitlab.com/JBBgameich/OpenBoard/commit/7179a33c0cbb6fe205d57ad854ddc5be4990e509
> (I just want to check whether preparing another pr makes sense)
> 
> This change should remove the need for the xpdf source code dump in the ThirdParty repository by using the proper library.

We are trying to make it possible for the "Ubuntu 18.04 support" build (should be the 1.5.4, planned for this summer, if I figure out the different issues we have with Gnome desktop)

**Comment by JBBgameich** [comment]
I started upstreaming some of my changes, it would be great if you could have a look.

One PR is about replacing deprecated Qt features, which starts becoming more important now that Qt6 is not so far away.

The other one is about porting to poppler and the third PR is only updating the translation files, which shouldn't need much review.

Thanks in advance :)

**Pull request closed without merging**
