### PR TITLE
Shortcut configuration

### PR DESCRIPTION
**Pull request by letsfindaway**
This pull request implements a flexible configuration of shortcuts for actions triggered by keyboard, special mouse buttons or tablet stylus buttons. It is still draft, as intensive testing is still needed. Here a description of what was added or changed:

- The preferences have a new Shortcut tab showing a list of actions and associated shortcuts.
- The actions are grouped. Grouping is hard-coded in the `UBShortcutManager` and can be extended there.
- The list can be filtered by typing any part of a description or shortcut.
- When an action is selected, the shortcuts for that action can be edited by "recording". This means, that you press the "Record" button and then any key combination, mouse button and/or stylus button you want to assign to that action. When finished, press "Accept" or "Abort". When accepted, the shortcut(s) are assigned to that action.
- You can reset the shortcuts to the application defaults using the "Reset" button.
- All mouse buttons except left and right and all stylus buttons can be used to trigger actions.
- When you type a conflicting shortcut, you will be warned and the offending entry is shown in the table.
- There is a checkbox to allow all shortcuts which are combinations using the Ctrl key also to be triggered without pressing Ctrl. If the Alt key is specified in a shortcut, this is unaffected by this checkbox.
- The configured state is persisted in the user settings.
- All shortcuts can also be triggered when the owning palette is not shown. I.e. it is no longer necessary to display the stylus palette in order to use Ctrl+I, Ctrl+E etc.

The pull request especially needs intensive testing on Windows and Mac, as I'm developing on Linux and do not have other platforms available for testing. Any feedback is highly appreciated!

My branch is based on the latest release candidate https://github.com/OpenBoard-org/OpenBoard/releases/tag/v1.6.1rc-0309, so all features and bug fixes of that release are also included.

### CODE REVIEW

**Review by letsfindaway — COMMENTED** [review]
I have seen that just by editing `resources/forms/preferences.ui` on my machine changed a lot of font and style information in the Credits and About tabs. If required I can change that so that just the new Shortcut tab is added.

**Comment by letsfindaway** [comment]
For testers using openSUSE Leap or Tumbleweed: Binary builds for the 1.6.1rc-03-09 including this PR are available at https://software.opensuse.org/package/OpenBoard as community packages.

**Comment by letsfindaway** [comment]
Adapted translation files to https://github.com/OpenBoard-org/OpenBoard/commit/181f3d9e9967815065040d95c4a0d6b4976959b3 and updated German translation

**Comment by letsfindaway** [comment]
Rebased to 1.7-dev as it is a candidate for that release.

**Comment by dhakiptk** [comment]
Eagerly waiting for this PR to be merged :-)

Will this fix [this](https://github.com/OpenBoard-org/OpenBoard/issues/542) as well?

**Comment by letsfindaway** [comment]
> Eagerly waiting for this PR to be merged :-)
> 
> Will this fix [this](https://github.com/OpenBoard-org/OpenBoard/issues/542) as well?

Yes, will be fixed by this PR, too.

**Comment by dhakiptk** [comment]
hi @letsfindaway , I've installed OB using your branch [shortcut-configuration](https://github.com/letsfindaway/OpenBoard/tree/shortcut-configuration) on my Ubuntu 20.04 LTS and I've configured a few shortcuts and also checked the checkbox "Active keyboard shortcuts without pressing Ctrl key".

However, when I start openboard, I NEED to press Ctrl key despite having checked the checkbox. 
If, however, I go to preferences once and close them(with or without making any changes), the shortcuts start to work without pressing the Ctrl key.

Here is a [video](https://www.youtube.com/watch?v=ddFoMc2g4Jc) for the same

**Comment by letsfindaway** [comment]
> hi @letsfindaway , I've installed OB using your branch [shortcut-configuration](https://github.com/letsfindaway/OpenBoard/tree/shortcut-configuration) on my Ubuntu 20.04 LTS and I've configured a few shortcuts and also checked the checkbox "Active keyboard shortcuts without pressing Ctrl key".
> 
> However, when I start openboard, I **NEED** to press Ctrl key despite having checked the checkbox mentioned above If, however, I open the preferences widow once and close it(with or without making any changes), the shortcuts start to work **without pressing the Ctrl key.**(as expected)
> 
> Here is a [video](https://www.youtube.com/watch?v=ddFoMc2g4Jc) for the same

Thanks for reporting! I really appreciate anybody testing this. I can reproduce this and already pushed a fix to this branch.

Note however that builds of this branch currently often crash during startup of OpenBoard due to a race condition in some code not related to the shortcut configuration. I'm sure @kaamui will fix that soon. After that, I will rebase my PR so that everything works fine.

**Comment by letsfindaway** [comment]
Sorry, seems that those fixes are already in 1.7-dev and I just needed to rebase my branch. Should be fine now!

**Comment by dhakiptk** [comment]
Thanks a lot for fixing this, I can confirm that this issue is fixed now. Is there a way to set the mouse scroll as a shortcut?
For e.g, I want to set up Mouse Scroll up as "zoom out" and Mouse Scroll down as "zoom in". Just saying, don't really bother if you think it is unnecessary.

I do ran up into some crashes which I verified were due to code changes in 1.7-dev branch.

Thanks a ton, I've got an almost perfect setup now. :-)

**Comment by letsfindaway** [comment]
With the latest commit, you can now also temporarily switch to another tool by pressing and holding down the shortcut key. After releasing, the previous tool will be selected again.

So e.g. while using the pen tool, you can press and hold Ctrl+E, erase some stuff, and then release the keys. You will then be back to the pen tool.

**Comment by letsfindaway** [comment]
> Is there a way to set the mouse scroll as a shortcut? For e.g, I want to set up Mouse Scroll up as "zoom out" and Mouse Scroll down as "zoom in". Just saying, don't really bother if you think it is unnecessary.

That was so easy to do and seems to me very useful, that I added this feature here with the latest commit. Also many other programs have this, so users might expect that from OpenBoard, too.

**Comment by TheMathGuyd** [comment]
The commits haven't gone through, but thank you greatly for making great improvements to the usability of this software. I see that it has been many months of work, and that most users will take these features for granted once they are included. I do not know how to support your work, but I would like to.

**Comment by letsfindaway** [comment]
Hi @TheMathGuyd,
I'm always committed to offer improvements to OpenBoard. However I cannot directly influence whether and when they are included.
Currently this pull request is targeted to 1.7-dev, because AFAIK 1.6.2 will be a pure bug fix release with no new features - configurable shortcuts would be a feature, of course.
However I can also rebase this PR and offer it to 1.6.2, if this is requested by the project maintainer. I could also split out the "mouse wheel" stuff into a separate PR, if this helps. Most of the other improvements are however closely linked to making shortcuts configurable. So this is some kind of package the project would have to take.

What would really help me:

- Pointing out what feature exactly you need and for what purpose. The project is always trying to include only features, which have relevance in practice. So any feature request saying "it would be cool to see this and that in OpenBoard" will likely fail, while a real use case for teaching is more convincing.
- Beta-testing my pull requests. I can only provide builds for some Linux distributions, not for Mac or Windows. But if you're able to build OpenBoard on your platform and try out how my pull requests work for you, this would be a great feedback. Issues with my PRs can be reported directly at [my fork](https://github.com/letsfindaway/OpenBoard/issues).

**Comment by TheMathGuyd** [comment]
Hi @letsfindaway,
 
Thanks, I will follow your fork to test when I have days off between lectures. 

For now, I will include my needs and reasons. The most important changes for me would be:
1. *Fix* the conflict between Scroll page (Ctrl+ArrowKey) and Next/Previous Page
  - This is keeping me from using third-party workarounds to navigate a page while zoomed in. 
2. *Add* Shortcut key (combinations) for Pen Colors 1,2,3,4,5
  - This is one of the most common reasons I have to reach outside of the drawing area, and it has started to affect my shoulder. To combat this, I use an (unsatisfying) automator service for each color.
3. *Change* or allow an alias for the shortcut for "New Page"
  - This is again one of the more common reasons I have to reach into the toolbar. (On MacOS at least) Pressing the "insert" key *does not add a page*, and just seems to mess up the other built-in shortcuts for a while.


I would comfortably be able to use OpenBoard with these changes, and I think others that are trying to minimize reaching to the bottom/top extremities of the screen will find relief as well. Even without a GUI for configuring shortcuts, I would get by with a macropad and some stickers. 


To write in general about the needs of a digital-lecturer, and how clearly defined shortcuts relate to them.
These shortcuts are *not just used by keyboard-users*. They can be run from presentation remotes in the hands of an individual at an interactive display (SmartBoard, Promethean, etc.) They could be run from foot pedals, especially useful for one-armed users. For this reason, extending the shortcuts to more functions would greatly improve the ergonomics and accessibility.

**Comment by letsfindaway** [comment]
Moved commits regarding mouse wheel handling into a new branch `feat-mouse-wheel` which will go into a separate PR. It should then support

- Scroll vertically with mouse wheel
- Scroll horizontally together with the `Alt` key
- Zoom in and out together with the `Ctrl` key

More information will come when I create that PR.

**Pull request merged**
