### PR TITLE
Update OpenBoard_hu.ts

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Review by Joonel — APPROVED** [review]

**Comment by ovari** [comment]
How can this be merged?

Thank you

**Comment by ovari** [comment]
@kaamui can you please merge this? If not, please advise so fork can be deleted. Thank you

**Comment by letsfindaway** [comment]
Please keep this PR. See https://github.com/OpenBoard-org/OpenBoard/issues/778#issuecomment-1594598478 for a rough time plan of kaamui for release. But let me give you some hints for updating your PR:

- First of all, the PR currently does not merge due to conflicts. You will have to rebase it to the current master. 
- Second, there are some more strings added and some removed during development of OpenBoard to the current status. This is currently not reflected in the TS files. I recommend to update the TS file as follows:
  - Check out the current `master` from the OpenBoard project.
  - Open a console at the project root directory and run the following command:<br>`lupdate . -ts resources/i18n/OpenBoard_hu.ts`<br>Depending on your environment the `lupdate` command may also be called `lupdate-qt5` or similar. It should be contained in the same directory where you find `qmake`.
  - This command updates the `.ts` file, marks obsolete translations as `vanished` and adds new translations.
  - Then base your improvements on this `.ts` file and probably add the new ones.

**Comment by ovari** [comment]
Thank you @letsfindaway for your comment.

This has been done entirely using a web-browser.

Can you please advise how to rebase with current master?

The other instructions don't seem to be possible using a web-browser.

Can this merge request be accepted and then those commands you wrote be done by someone who does not use a web-browser so that this repository can be merged again with updates to send back?

Thank you

**Comment by ovari** [comment]
Hopefully the conflicts are now fixed.

@letsfindaway can this merge request please now be merged? Then this fork can be deleted. Once there is a request for translator to check again, a fork can be created of the up-to-date strings which are included in the dev branch.

Thank you

**Comment by letsfindaway** [comment]
For merging, we have to wait for kaamui. I'm also just a contributor and not part of the project, so I cannot do this.

If you already want to update the translations, I have executed the above-mentioned commands for you and attached the result here. So if you apply your changes to this file, it will fit to the upcoming release. You will find some new strings in this file, which have been added in the meantime.

[OpenBoard_hu.zip](https://github.com/OpenBoard-org/OpenBoard/files/12269125/OpenBoard_hu.zip)

**Comment by ovari** [comment]
Thank you @letsfindaway for your information. Closing. Thank you once again.

**Comment by kaamui** [comment]
Hi @ovari and sorry for the late reply.

The 1.7 has been merged in the master. You should be able to update your translations easier now.

Also, please read this thread => #794

**Pull request closed without merging**
