### PR TITLE
Allow configurable Shortcuts

### PR DESCRIPTION
**Pull request by ootwch**
Moved most shortcuts into actions or shortcuts.
Added a new UI in Preferences to edit shortcuts.

Added two more shortcuts "Color Rotate" and "Width Rotate" to rotate through color/width on the keyboard.

The edit interface is a bit crude, but I have not found a good way to do this with a QTableView instead.

Caveats from my other PR applies: Not a Qt or CPP developer.

### CODE REVIEW

**Comment by kaamui** [comment]
hello,

Thank you (again !) for your help !

Same comment though, I can't try what you did because of all the commits non-related to the new feature. Can you make a PR with just the related commits ? I can help with git if needed

**Comment by ootwch** [comment]
Hi,

And thanks for considering the PR's! I will try ot clean them up this
weekend.. won't manage earlier, however.

I also have some more things I will put in, will try to have it cleaned up
beforehand ;-)

It looks like you have already taken the XPDF things?

**Comment by kaamui** [comment]
hello,

Yes. I could not make poppler work. I'll retry later. I mentioned you in the commit message and I'll mention you in the changelog.

Thank you for all your work, I'll look at it the other PRs asap.

**Comment by ootwch** [comment]
Replaced with new (cleaned up) PR.

**Pull request closed without merging**
